export const CARDS_DECK_DATA = [
  {
    suit: "hearts",
    label: "2",
    order: 2,
    points: 2,
  },
  {
    suit: "hearts",
    label: "3",
    order: 3,
    points: 3,
  },
  {
    suit: "hearts",
    label: "4",
    order: 4,
    points: 4,
  },
  {
    suit: "hearts",
    label: "5",
    order: 5,
    points: 5,
  },
  {
    suit: "hearts",
    label: "6",
    order: 6,
    points: 6,
  },
  {
    suit: "hearts",
    label: "7",
    order: 7,
    points: 7,
  },
  {
    suit: "hearts",
    label: "8",
    order: 8,
    points: 8,
  },
  {
    suit: "hearts",
    label: "9",
    order: 9,
    points: 9,
  },
  {
    suit: "hearts",
    label: "10",
    order: 10,
    points: 10,
  },
  {
    suit: "hearts",
    label: "J",
    order: 11,
    points: 10,
  },
  {
    suit: "hearts",
    label: "Q",
    order: 12,
    points: 10,
  },
  {
    suit: "hearts",
    label: "K",
    order: 13,
    points: 10,
  },
  {
    suit: "hearts",
    label: "A",
    order: 14,
    points: 10,
  },
  {
    suit: "diamonds",
    label: "2",
    order: 2,
    points: 2,
  },
  {
    suit: "diamonds",
    label: "3",
    order: 3,
    points: 3,
  },
  {
    suit: "diamonds",
    label: "4",
    order: 4,
    points: 4,
  },
  {
    suit: "diamonds",
    label: "5",
    order: 5,
    points: 5,
  },
  {
    suit: "diamonds",
    label: "6",
    order: 6,
    points: 6,
  },
  {
    suit: "diamonds",
    label: "7",
    order: 7,
    points: 7,
  },
  {
    suit: "diamonds",
    label: "8",
    order: 8,
    points: 8,
  },
  {
    suit: "diamonds",
    label: "9",
    order: 9,
    points: 9,
  },
  {
    suit: "diamonds",
    label: "10",
    order: 10,
    points: 10,
  },
  {
    suit: "diamonds",
    label: "J",
    order: 11,
    points: 10,
  },
  {
    suit: "diamonds",
    label: "Q",
    order: 12,
    points: 10,
  },
  {
    suit: "diamonds",
    label: "K",
    order: 13,
    points: 10,
  },
  {
    suit: "diamonds",
    label: "A",
    order: 14,
    points: 10,
  },
  {
    suit: "clubs",
    label: "2",
    order: 2,
    points: 2,
  },
  {
    suit: "clubs",
    label: "3",
    order: 3,
    points: 3,
  },
  {
    suit: "clubs",
    label: "4",
    order: 4,
    points: 4,
  },
  {
    suit: "clubs",
    label: "5",
    order: 5,
    points: 5,
  },
  {
    suit: "clubs",
    label: "6",
    order: 6,
    points: 6,
  },
  {
    suit: "clubs",
    label: "7",
    order: 7,
    points: 7,
  },
  {
    suit: "clubs",
    label: "8",
    order: 8,
    points: 8,
  },
  {
    suit: "clubs",
    label: "9",
    order: 9,
    points: 9,
  },
  {
    suit: "clubs",
    label: "10",
    order: 10,
    points: 10,
  },
  {
    suit: "clubs",
    label: "J",
    order: 11,
    points: 10,
  },
  {
    suit: "clubs",
    label: "Q",
    order: 12,
    points: 10,
  },
  {
    suit: "clubs",
    label: "K",
    order: 13,
    points: 10,
  },
  {
    suit: "clubs",
    label: "A",
    order: 14,
    points: 10,
  },
  {
    suit: "spades",
    label: "2",
    order: 2,
    points: 2,
  },
  {
    suit: "spades",
    label: "3",
    order: 3,
    points: 3,
  },
  {
    suit: "spades",
    label: "4",
    order: 4,
    points: 4,
  },
  {
    suit: "spades",
    label: "5",
    order: 5,
    points: 5,
  },
  {
    suit: "spades",
    label: "6",
    order: 6,
    points: 6,
  },
  {
    suit: "spades",
    label: "7",
    order: 7,
    points: 7,
  },
  {
    suit: "spades",
    label: "8",
    order: 8,
    points: 8,
  },
  {
    suit: "spades",
    label: "9",
    order: 9,
    points: 9,
  },
  {
    suit: "spades",
    label: "10",
    order: 10,
    points: 10,
  },
  {
    suit: "spades",
    label: "J",
    order: 11,
    points: 10,
  },
  {
    suit: "spades",
    label: "Q",
    order: 12,
    points: 10,
  },
  {
    suit: "spades",
    label: "K",
    order: 13,
    points: 10,
  },
  {
    suit: "spades",
    label: "A",
    order: 14,
    points: 10,
  },
];

export const BASE_BLINDS = [300, 800, 2000, 5000, 11000, 20000, 35000, 50000];

export const BASE_POKER_HANDS_VALUES = [
  { id: "straight-flush", name: "Quinte flush", points: 100, multiplier: 8 },
  { id: "four-of-a-kind", name: "Carré", points: 60, multiplier: 7 },
  { id: "full-house", name: "Main pleine", points: 40, multiplier: 4 },
  { id: "flush", name: "Couleur", points: 35, multiplier: 4 },
  { id: "straight", name: "Suite", points: 30, multiplier: 4 },
  { id: "three-of-a-kind", name: "Brelan", points: 30, multiplier: 3 },
  { id: "two-pairs", name: "Double paire", points: 20, multiplier: 2 },
  { id: "pair", name: "Paire", points: 10, multiplier: 2 },
  { id: "high-card", name: "Carte haute", points: 5, multiplier: 1 },
];
